#!/bin/bash 

--[[
#      ▇▇▇                                       ▇▇▇               ▄▇▇▇▇▇▄                 ▇▇                                    ▇▇                
#      ▇▇        ▇                        ▇       ▇▇             ▄▇                ▇▄                        ▇▇                  ▇▇
#      ▇▇          ▇ @sajad14p   ▇         ▇▇            ▄▇▄▄▄▄▄▇▄                               ▇▇ ▇▇
#      ▇▇             ▇             ▇             ▇▇        ▄▇                            ▇▄                          ▇▇ ▇▇ ¦ Dev : @sajad14p
#      ▇▇                ▇       ▇                ▇▇      ▄▇ ¦ Dev : @YYBYY  ▇▄                 ▇▇                 ▇▇
#      ▇▇                   ▇▇                    ▇▇     ▄▇                                    ▇▄      ▇▇                                  ▇▇¦ Source @YYBYY
#---------------------------------------------------------------------
cd $(cd $(dirname $0); pwd)
Day_now=$(date +%F)
RED='\033[0;31m'
SMAY='\033[0;36m'
GREEN='\033[0;32m'
Yellow='\033[0;33m'
LSAMAY='\033[01;49m'
WHITB='\033[01;90m'
WHITEC='\033[01;91m'
CNIL='\033[0m'

Version=`lsb_release -rs | cut -f1 -d"."`

if [ "$Version" == "18" ];then
echo -e "${SMAY}\n"
echo -e " ▇▇▇                                       ▇▇▇               ▄▇▇▇▇▇▄                 ▇▇                                    ▇▇"
echo -e " ▇▇        ▇                        ▇       ▇▇             ▄▇                ▇▄                        ▇▇                  ▇▇"
echo -e " ▇▇          ▇ @sajad14p   ▇         ▇▇            ▄▇▄▄▄▄▄▇▄                               ▇▇ ▇▇"
echo -e " ▇▇             ▇             ▇             ▇▇        ▄▇                            ▇▄                          ▇▇ ▇▇ ¦ Dev : @sajad14p"
echo -e " ▇▇                ▇       ▇                ▇▇      ▄▇ ¦ Dev : @YYBYY  ▇▄                 ▇▇                 ▇▇"
echo -e " ▇▇                   ▇▇                    ▇▇     ▄▇                                    ▇▄      ▇▇                                  ▇▇¦ Source @YYBYY"
echo -e " ----------------------------------------------------------------------"
echo -e "${CNIL}"
echo -e "${RED}| للاسف لايمكنك تنصيب السورس ع نظام اوبنتو {${Version}} يجب ان يكون على اصدار  اقل مثلا  ${SMAY}14 او 16
${CNIL}";
echo -e "${RED}| Sorry Canot installtall Source on Ubuntu {${Version}} Please installtall system To Ubuntu ${SMAY}14 or 16 ${RED} For BS The Source brothers 
${CNIL}";
exit;
fi

echo -e "${SMAY}\n"
echo -e " ▇▇▇                                       ▇▇▇               ▄▇▇▇▇▇▄                 ▇▇                                    ▇▇"
echo -e " ▇▇        ▇                        ▇       ▇▇             ▄▇                ▇▄                        ▇▇                  ▇▇"
echo -e " ▇▇          ▇ @sajad14p   ▇         ▇▇            ▄▇▄▄▄▄▄▇▄                               ▇▇ ▇▇"
echo -e " ▇▇             ▇             ▇             ▇▇        ▄▇                            ▇▄                          ▇▇ ▇▇ ¦ Dev : @sajad14p"
echo -e " ▇▇                ▇       ▇                ▇▇      ▄▇ ¦ Dev : @YYBYY  ▇▄                 ▇▇                 ▇▇"
echo -e " ▇▇                   ▇▇                    ▇▇     ▄▇                                    ▇▄      ▇▇                                  ▇▇¦ Source @YYBYY"
echo -e " ----------------------------------------------------------------------"
echo -e "${CNIL}"

memory_free=`awk '/^Mem/ {print $4}' <(free -m)`

if [ "$memory_free" -le 60 ]; then
echo -e "${RED}¦
¦ CAUTION:${WHITEC} Your RAM size is less than 60MB.
¦ NOW you can not installtall the SOURCE brothers. \n
¦${WHITB}¦ YOUR RAM FREE SIZE IS : ${SMAY}${memory_free}MB${CNIL}"
exit ;
fi


PKG_OK=`/usr/bin/dpkg-query --show --showformat='${db:Status-Status}\n' 'redis-server'`
if [ "${PKG_OK}" == "installtalled" ]; then
if [ "$1" == "-R" ] ; then
GET_INSTALL="NO"
else
GET_INSTALL=$(redis-cli get brothers_INSTALL)
fi
if [ "${GET_INSTALL}" == "Yes" ]; then
echo -e "
${SMAY}>> ${LSAMAY}Source brothers${SMAY} is Already Installed ^_^ .\n${CNIL}"
sudo luarocks installtall luautf8
sudo chmod +x ./bs
sudo chmod +x ./TG
sudo ./bs
exit;
fi 
fi

echo -e "${WHITB}\n¦ installtalling source ... \n\n\n\n${CNIL}"
sudo apt-get update -y
sudo apt-get upgrade -y
echo -e "\x1B[01;90m\n¦ software-properties-common installtalling ... \n\x1B[0m"
sudo apt-get installtall software-properties-common -y
echo -e "\x1B[01;90m\n¦ ubuntu-toolchain installtalling ...\n \x1B[0m"
sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
# BY _ [ SAJAD >> @sajad14p | GLOBLA >> @YYBYY ]
echo -e "\x1B[01;90m\n¦ installtall luarocks v2.4.3 ... \n\x1B[0m"
sudo  wget https://luarocks.org/releases/luarocks-2.4.3.tar.gz
sudo  tar zxpf luarocks-2.4.3.tar.gz
cd luarocks-2.4.3
echo -e "\x1B[01;90m\n¦ ./configure AND make bootstrap ...\n \x1B[0m"
./configure; sudo make bootstrap
sudo luarocks installtall luasocket
echo -e "\x1B[01;90m\n¦ luasocket installtalling ...\n \x1B[0m"
sudo luarocks installtall luasec
sudo luarocks installtall luautf8
echo -e "\x1B[01;90m\n¦ redis-lua installtalling ... \n\x1B[0m"
sudo luarocks installtall redis-lua
echo -e "\x1B[01;90m\n¦ lua-cjson installtalling ... \n\x1B[0m"
sudo  luarocks remove lua-cjson2
sudo  luarocks remove lua-cjson
sudo  apt-get installtall lua-cjson
echo -e "\x1B[01;90m\n¦ Lua-cURL installtalling ...\n \x1B[0m"
sudo luarocks installtall Lua-cURL
echo -e "\x1B[01;90m\n¦ redis-server start ...\n \x1B[0m"
sudo service redis-server start
sudo apt-get update -y
echo -e "\x1B[01;90m\n¦  g++-4.7 -y c++-4.7 installtalling ... \n\x1B[0m"
sudo apt-get installtall g++-4.7 -y c++-4.7
echo -e "\x1B[01;90m\n¦ luasocket installtalling ...\n \x1B[0m"
sudo apt-get installtall libreadline-dev -y libconfig-dev -y libssl-dev -y lua5.2 -y liblua5.2-dev -y lua-socket -y lua-sec -y lua-expat -y libevent-dev -y make unzip git redis-server autoconf g++ -y libjansson-dev -y libpython-dev -y expat libexpat1-dev -y curl -y htop -y
echo -e "\x1B[01;90m\n¦ screen installtalling ... \n\x1B[0m"
sudo apt-get installtall screen -y
echo -e "\x1B[01;90m\n¦ libstdc++6 installtalling ... \n\x1B[0m"
sudo apt-get installtall libstdc++6 -y
echo -e "\x1B[01;90m\n¦ lua-lgi installtalling ... \n\x1B[0m"
sudo apt-get installtall lua-lgi -y
echo -e "\x1B[01;90m\n¦ libnotify installtalling ... \n\x1B[0m"
sudo apt-get installtall libnotify-dev -y
cd ..
echo -e "\x1B[01;90m\n¦ Remove luarocks ... \n\x1B[0m"
sudo rm -fr ./luarocks-2.4.3
sudo rm -fr ./luarocks-2.4.3.tar.gz
echo -e "${WHITB}\n¦ Convert TimeZone To Asia/Baghdad  ... \n${CNIL}"
sudo timedatectl set-timezone Asia/Baghdad
sudo chmod +x TG
sudo chmod +x bs
sudo chmod +x ./bs
echo -e "\n
${SMAY}>> Installation ${LSAMAY}Source brothers${SMAY} Completed ^_^ .\n
Now I Have Information For Your Bot  \n
1- Enter Token Your Bot .
2- Enter Your UserName Sudo .
3- And End Press Enter To BS Source brothers .\n\n
${RED}Note:${Yellow} Send \"/start\"${SMAY} To Your Bot For Show All Commands.${CNIL}"
sudo ./bs
